### ISSUE TITLE
(solved) Error! Could not locate dkms.conf file. File:  does not exist.

### ISSUE THREAD

**Issue by danithechief** [morrownr/8812au#19]
I have this error:

Error! Could not locate dkms.conf file.
File:  does not exist.

someone can help plz?

Installing rtl8812au-5.9.3.2
Copying source files to: /usr/src/rtl8812au-5.9.3.2
Copying 8812au.conf to: /etc/modprobe.d
Error! DKMS tree already contains: rtl8812au-5.9.3.2
You cannot add the same module/version combo more than once.
An error occurred while running: dkms add : 3
Removing 8812au.conf from: /etc/modprobe.d
Removing source files from: /usr/src/rtl8812au-5.9.3.2
Cleanup complete
dkms status:
8812au, 150821: added
Error! Could not locate dkms.conf file.
File:  does not exist.

its a zorin machine (Ubuntu 18 i think)

**Comment by morrownr** [comment]
Run:

$ sudo ./remove-driver.sh

and then follow the installation instructions again.

The driver was already installed when you tried to install it. I'm not sure how that came about but I will look into reworking the installation script logic.

**Comment by danithechief** [comment]
I know how. I have already installed some time before...

Thx bro i will try later

Von meinem iPhone gesendet

Am 22.03.2021 um 22:34 schrieb morrownr ***@***.***>:

﻿

Run:

$ sudo ./remove-driver.sh

and then follow the installation instructions again.

The driver was already installed when you tried to install it. I'm not sure how that came about but I will look into reworking the installation script logic.

**Comment by morrownr** [comment]
I have reworked and tested a new version of the installation script. It should prevent inadvertent installation attempts over previous installations.

**Comment by danithechief** [comment]
You are the King💪
The reason why ive installed it twice is, because i tought it was an update.
Because on my zorin os the Driver dont work stable…

thx



Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: ***@***.***>
Gesendet: Samstag, 27. März 2021 07:02
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [morrownr/8812au] Error! Could not locate dkms.conf file. File: does not exist. (#19)


I have reworked and tested a new version of the installation script. It should prevent inadvertent installation attempts over previous installations.
